[package]
name = "op-env"
version = "0.0.3"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
dotenvy = "0.15.7"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
shell-escape = "0.1.5"
thiserror = "1.0.65"
