use chrono;
use std::collections::HashMap;
use std::env;
use std::process::Command;

fn main() {
    let mut env_vars = HashMap::new();

    // Retrieve all environment variables that contain "op:" in their name.
    for (key, value) in env::vars() {
        if value.contains("op:") {
            env_vars.insert(key, value);
        }
    }

    // Retrieve all secrets from 1Password without masking.
    let output = Command::new("op")
        .arg("run")
        .arg("--no-masking")
        .arg("--")
        .arg("printenv")
        .output()
        .expect("failed to execute process");
    let stdout = String::from_utf8(output.stdout).unwrap();

    println!("# Generated by op-env on {now}", now = chrono::Local::now());

    // Print all export statements for the environment variables that need
    // replacement.
    for line in stdout.lines() {
        let split: Vec<&str> = line.split("=").collect();

        if split.len() != 2 {
            continue;
        }

        let key = split[0];
        let value = split[1];

        if env_vars.contains_key(key) {
            println!("export {key}=\"{value}\"");
        }
    }
}
