use chrono;
use std::env;
use std::process::Command;

fn has_command(bin: &str) -> bool {
    let binding = env::var("PATH").unwrap();
    let paths = binding.split(":");

    for dir in paths {
        let path = format!("{}/{}", dir, bin);

        if std::path::Path::new(&path).exists() {
            return true;
        }
    }

    return false;
}

fn main() {
    if !has_command("op") {
        println!("ERROR: op command not found");
        std::process::exit(1);
    }

    let mut vars = std::vec::Vec::new();

    // Aggregate all environment variables that contain "op:" in their value.
    for (key, value) in env::vars() {
        if value.contains("op:") {
            vars.push(key);
        }
    }

    // Retrieve all secrets from 1Password without masking.
    let output = Command::new("op")
        .arg("run")
        .arg("--no-masking")
        .arg("--")
        .arg("printenv")
        .output()
        .expect("failed to execute `op` command");

    let stdout = String::from_utf8(output.stdout).unwrap();

    println!("# Generated by op-env on {now}", now = chrono::Local::now());

    // Print all export statements for the environment variables that need
    // replacement.
    for line in stdout.lines() {
        match line.split_once("=") {
            Some((key, value)) => {
                if vars.contains(&key.to_string()) {
                    println!("export {key}=\"{value}\"");
                }
            }
            None => {
                continue;
            }
        }
    }
}
